FontAtlas.go
FontAtlasWrapper.cpp
FontAtlasWrapper.h
FontConfig.go
FontConfigWrapper.cpp
FontConfigWrapper.h

Adds functions to create and delete FontConfig objects and set basic properties.
The `(cfg *FontConfig) Delete` function resets the `FontConfig` handle to 0 / `nullptr` / the default configuration after deleting the C object and the other functions check the passed handle to avoid double-frees and null dereferences.
(For previous discussion see #26)

Add basic FontConfig implementation

---

Style.go

While using SetColor to change some colors, noticed that some colors don't change, but affects other unrelated color, which turns out to be due to missing StyleColorID values and some wrong order at the end.

Add missing StyleColorID enum values and fix wrong order

---

Vectors.go

For example this:
```
cursor := imgui.CursorScreenPos()
padding := style.FramePadding()
x, y := cursor.X + padding.X, cursor.Y + padding.Y
w, h := size.X - 2 * padding.X, size.Y - 2 * padding.Y
drawList.AddRectFilled(cursor, imgui.Vec2{X:cursor.X + size.X, Y:cursor.Y+size.Y}, 0xff800000)
drawList.AddLine(imgui.Vec2{X: x, Y: y}, imgui.Vec2{X: x+ w, Y: y +h}, 0xff00ff88)
```
turns into this:
```
cursor := imgui.CursorScreenPos()
padding := style.FramePadding()
start := cursor.Plus(padding)
innerSize := size.Minus(padding.Times(2))
drawList.AddRectFilled(cursor, cursor.Plus(size), 0xff800000)
drawList.AddLine(start, start.Plus(innerSize), 0xff00ff88)
```
Works nicely with inline getters and setters as well:
```
imgui.SetCursorPos(imgui.CursorPos().Plus(imgui.Vec2{Y: padY}))
```

Add simple math operations to vector types

---

SelectableFlags.go
imgui.go

Since the `flags` parameters are all of type `int` it is not very clear what values are valid.
I also added the definitions for the [`SelectableFlags`](https://github.com/inkyblackness/imgui-go/blob/master/imgui.h#L778) since they were missing.

Improve documentation

---

FontAtlas.go
FontAtlasWrapper.cpp
FontAtlasWrapper.h
FontConfig.go
FontConfigWrapper.cpp
FontConfigWrapper.h
WindowFlags.go

This PR "depends" on #55.
This PR exposes the `AddFontFromMemoryTTF` function in the Go API. This allows loading of fonts from memory.

Expose AddFontFromMemoryTTF

---

FreeType.go
FreeTypeWrapper.cpp
FreeTypeWrapper.h
go.mod
imgui_freetype.cpp
imgui_freetype.h

This PR "depends" on #57.
This PR exposes the FreeType rasterizer from the ImGui repo: https://github.com/ocornut/imgui/tree/master/misc/freetype in Go. FreeType is linked using `pkg-config`, this means that it is linked if and only if the user uses the API and the user can decide to link statically or dynamically by providing the right pkgconfig.

Add FreeType rasterizer

---

DrawList.go
DrawListWrapper.cpp
DrawListWrapper.h
Style.go
StyleWrapper.cpp
StyleWrapper.h
imgui.go
imguiWrapper.cpp
imguiWrapper.h
imguiWrapperTypes.h

added Style.FramePadding()
added IsItemClicked(), FrameHeight*() and InvisibleButton*()
added DrawList(), AddCircle*() and AddRect*()

Additional ImGui functions

---

AllocatedGlyphRanges.go
FontAtlas.go
GlyphRanges.go
InputTextCallbackData.go
WrapperConverter.go

As part of this, these casts were centralized, with an explanation what to do. The compiler most likely inlines them again, anyway.
This fixes #84 and #113 .

fixed build error on 32bit systems with pointer-to-slice casts

---

Window.go
wrapper/Window.cpp
wrapper/Window.h

Provide access to the window content region boundary.
These are helpful when trying to map from a mouse position back
to a coordinate within the content of a window - particularly
if the window is scrolling over larger content.

Add support for WindowContentRegion{Min,Max,Width}

---

FontConfig.go
wrapper/FontConfig.cpp
wrapper/FontConfig.h

IMGUI will synthesize a diagnostic name for fonts added from files
(eg "foo.ttf, 16px") if there isn't a name provided in the FontConfig.
There isn't an equivalent synthetic name for fonts added from memory,
so enable the name to be set on the FontConfig.
The names are visible in the Dear Imgui Demo window
under Configuration / Style, in the Fonts drop-list.

Add support for setting a FontConfig name

---

Widgets.go
wrapper/Widgets.cpp
wrapper/Widgets.h

This allows TreeNode flags to be passed along. In particular it's useful for having headers default to open:
```
if imgui.CollapsingHeaderV("Header", imgui.TreeNodeFlagsDefaultOpen) {
// ....
}
```

Add CollapsingHeaderV with flags parameter

---

DrawList.go
wrapper/DrawList.cpp
wrapper/DrawList.h

- add AddImage and AddImage v methods for adding textures to draw lists
- add BackgroundDrawList function to access drawlist of the background behind all the windows.
Those functions make it easier to use imgui-go as a generic OpenGL canvas.

Add a few more DrawList functions

---

Condition.go
DragDrop.go
DrawList.go
FreeType.go
IO.go
InputTextCallbackData.go
Popup.go
State.go
Style.go
Tables.go
Widgets.go
Window.go

Values in Condition.go do not have the correct type.
Only ConditionAlways has the correct Condition type. The Condition type is defined in the same file.
The other values are all of type int. This means those values must be cast to the Condition type in those places where you would expect them to be used. For example, SetNextWindowPosV()
Same comments for other constants.

Constants given correct type.

---

IO.go
wrapper/IO.cpp
wrapper/IO.h

This allows applications to disable the OS cursor and have imgui draw
custom cursors instead. (There's already some built-in for resizing
and text inputs)

Expose MouseDrawCursor

---

DrawList.go
wrapper/DrawList.cpp
wrapper/DrawList.h

Add `PushClipRect(min, max Vec2)`, `PushClipRectV(min, max Vec2, intersectWithCurrentClipRect bool)` and `PopClipRect()` to the DrawList API.

Added PushClipRect and PopClipRect

---

_licenses/imgui-LICENSE.txt
update_imgui.sh

This is especially useful for tracking non-release branches like the
"docking" branch.

Add small script to make updating imgui a little easier

---

DrawCommand.go
IO.go
wrapper/DrawCommand.cpp
wrapper/DrawCommand.h
wrapper/IO.cpp
wrapper/IO.h

I'll make a companion change to imgui-go-examples that updates the
opengl3 backend
(This is needed as part of my work to support `implot` which can create some huge vertex lists)

Expose VtxOffset to allow backends to render more than 64k vertices

---

DrawData.go
wrapper/DrawData.cpp
wrapper/DrawData.h

Reference: https://github.com/ocornut/imgui/blob/d9b606672ae145457d12dacdc82b82c6ce9ebd79/imgui.h#L2498
For consistency with the existing `IO.SetDisplayFrameBufferScale()` function, the capitalization of `FrameBuffer` was changed compared to the imgui sources.

Add getters for draw data sizes

---

README.md
Widgets.go

Fixes #168 
I've looked looked for all places which had `va_args` overloads in Dear ImGui. 
I think it's worth to add every such "wrapper" function, because people porting their code from C++ to Go might have easier time adjusting their code as-is. :)

Add string formatting overloads for Text, LabelText, TreeNode, SetTooltip

---

DrawList.go
wrapper/DrawList.cpp
wrapper/DrawList.h

* I am making an emulator with golang and imgui-go in my project.
* In the process, I wanted to use imgui to draw text on the Foreground.
* Do I need to update [inkyblackness/imgui-go-examples](https://github.com/inkyblackness/imgui-go-examples) ?
* From [CONTRIBUTION.md](https://github.com/inkyblackness/imgui-go/blob/main/CONTRIBUTING.md)
* link to GetForegroundDrawList functions
* https://github.com/ocornut/imgui/blob/master/imgui.cpp#L3813-L3822
* refs commit
* `Renamed GetOverlayDrawList() to GetForegroundDrawList() for consistency. Kept redirection function (will obsolete)`
* https://github.com/ocornut/imgui/commit/94e794f81be1bd31c843b4fa94f5235e6e97e366
```golang
imgui.ForegroundDrawList().
AddText(
imgui.Vec2{X: 10, Y: 10},
imgui.PackedColor(0xFFFFFFFF),
"Hi, this text is \ndrawn …
```

Support GetForegroundDrawList

---

.github/workflows/tests.yml
DrawList.go
Font.go
FontAtlas.go
README.md
State.go
wrapper/DrawList.cpp
wrapper/DrawList.h
wrapper/Font.cpp
wrapper/Font.h
wrapper/FontAtlas.cpp
wrapper/FontAtlas.h
wrapper/State.cpp
wrapper/State.h
wrapper/Types.h

Many thanks for the imgui-go wrapper--I've found it super useful!
I needed access to imgui's FontGlyph functionality so wired up support for that; here it is, if it's of interest.

Add support for FontGlyph
