inkyblackness/imgui-go

- IO.go
- IOWrapper.cpp
- IOWrapper.h
- _examples/opengl3_example/imgui-go_impl_glfw_gl3.go
- imgui.go
Hi,
I needed keyboard support so I thought I will give it a go.
Please let me know if you want to add this to your master.
> added keyboard support

- WrapperConverter.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Hi there. 
thanks for the work with this library. It's super handy!
this pull-request implements a couple of different inputs:
1. DragInt
2. DragFloat
3. SliderFloat
> Float sliders

- InputText.go
- InputTextCallbackDataWrapper.cpp
- InputTextCallbackDataWrapper.h
- WrapperConverter.go
- WrapperConverter_test.go
- doc.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
- imguiWrapperTypes.h
> Input text support

- AllocatedGlyphRanges_test.go
- IO.go
- IOWrapper.cpp
- IOWrapper.h
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Added support for two imgui functions:
SetScrollHereY and io.SetIniFilename
> SetIniFilename and ScrollHereY

- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Adds the following functions:
- `PlotLines()` and `PlotLinesV()`
- `PlotHistogram()` and `PlotHistogramV()`
> Add plotting functions

- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Implements the following functions:
- `WindowPos()`
- `WindowSize()`
- `WindowWidth()`
- `WindowHeight()`
- `CalcItemWidth()`
- `CursorPos()`
- `CursorPosX()`
- `CursorPosY()`
- `ContentRegionAvail()`
> Add some utility functions

- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Add ImGui GetTreeNodeToLabelSpacing as TreeNodeToLabelSpacing
> add TreeNodeToLabelSpacing

- TabBarFlags.go
- TabItemFlags.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
This is the correct pull request for TabBar and TabItem bindings. Pull request #51 falsely used the master branch.
> Provide bindings for TabBar and TabItem

- WindowFlags.go
This PR adds a constant that was missing in the Go API.
> Add WindowFlagsNoBackground

- FreeType.go
- FreeTypeDisabled.go
- FreeTypeEnabled_linux.go
- FreeTypeError.go
- FreeTypeWrapper.cpp
- FreeTypeWrapper.h
- README.md
- imgui_freetype.cpp
- imgui_freetype.h
> Add FreeType support

- ColorEditFlags.go
- ColorPickerFlags.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Small PR for adding the ImGui widgets ColorEdit and ColorPicker
> Add ColorEdit and ColorPicker widgets

- FocusedFlags.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Added 4 IsWindow functions - IsWindowAppearing, IsWindowCollapsed, IsWindowFocuseddepending, IsWindowHovered
> Add IsWindowXYZ 4 functions

- IO.go
- IOWrapper.cpp
- IOWrapper.h
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Small PR for some IO() props and IsItemActive().
> Add IO() properties and IsItemActive()

- .github/workflows/tests.yml
Starting to create a workflow.
I expect the initial version to fail at least on MS Windows, as probably no mingw will be available.
> first attempt of workflow

- InputText.go
- imgui.go
- imguiWrapper.cpp
- imguiWrapper.h
Changes for issues #75, #77 and #78
> New functions and bug fix

- State.go
- wrapper/State.cpp
- wrapper/State.h
Fixes #116 
I have tested this and it seems to work correctly, but I don't know cpp well.
> Add GetItemRectMax/Min

- Main.go
- wrapper/Main.cpp
- wrapper/Main.h
> add ImGui::GetTime()

- Window.go
- wrapper/Window.cpp
- wrapper/Window.h
Adds PushButtonRepeat() and PopButtonRepeat() into Window.go
> Add push/pop button repeat

- Condition.go
- ListClipper.go
- Main_test.go
- Popup.go
- README.md
- Widgets.go
- imgui/imconfig.h
- imgui/imgui.cpp
- imgui/imgui.h
- imgui/imgui_demo.cpp
- imgui/imgui_draw.cpp
- imgui/imgui_internal.h
- imgui/imgui_widgets.cpp
- imgui/imstb_textedit.h
- imgui/misc/freetype/imgui_freetype.cpp
- wrapper/ListClipper.cpp
- wrapper/Popup.cpp
- wrapper/Popup.h
- wrapper/Widgets.cpp
- wrapper/Widgets.h
- Dear ImGui updated to v1.79
- Ported some of the API to be compatible with the new version
- Extended Drag*/Slider* API
> Update to v1.79

- DrawList.go
- wrapper/DrawList.cpp
> AddImageQuad

- .github/workflows/tests.yml
- DrawList.go
- wrapper/DrawList.cpp
- wrapper/DrawList.h
- wrapper/Types.h
> Add image quad
